<?php

use App\Models\Classes;
use App\Models\Qrcode;
use App\Models\Schedule;
use App\Models\User;
use Illuminate\Support\Str;

beforeEach(function () {
    $this->class = Classes::create(['grade' => '10', 'label' => 'A']);
    $this->teacherUser = User::factory()->create(['user_type' => 'teacher']);
    $this->teacher = $this->teacherUser->teacherProfile()->create(['nip' => 'T1']);

    $this->schedule = Schedule::create([
        'day' => 'Monday',
        'start_time' => '07:00',
        'end_time' => '09:00',
        'teacher_id' => $this->teacher->id,
        'class_id' => $this->class->id,
        'semester' => 1,
        'year' => 2026,
    ]);
});

test('teacher can scan student qr for their own schedule', function () {
    // QR generated by a student (class officer)
    $officerUser = User::factory()->create(['user_type' => 'student']);
    $officerUser->studentProfile()->create([
        'class_id' => $this->class->id,
        'nis' => 'S1',
        'is_class_officer' => true,
    ]);

    $qr = Qrcode::create([
        'token' => Str::uuid(),
        'schedule_id' => $this->schedule->id,
        'type' => 'student', // Targeted at students
        'issued_by' => $officerUser->id,
        'is_active' => true,
        'expires_at' => now()->addMinutes(15),
    ]);

    $response = $this->actingAs($this->teacherUser)
        ->postJson('/api/attendance/scan', [
            'token' => $qr->token,
        ]);

    $response->assertOk();
    $this->assertDatabaseHas('attendances', [
        'schedule_id' => $this->schedule->id,
        'teacher_id' => $this->teacher->id,
        'attendee_type' => 'teacher',
        'status' => 'present',
    ]);
});

test('teacher cannot scan student qr for OTHER teacher schedule', function () {
    $otherTeacherUser = User::factory()->create(['user_type' => 'teacher']);
    $otherTeacherUser->teacherProfile()->create(['nip' => 'T2']);

    // QR for the original schedule (owned by $this->teacher)
    $qr = Qrcode::create([
        'token' => Str::uuid(),
        'schedule_id' => $this->schedule->id,
        'type' => 'student',
        'is_active' => true,
        'expires_at' => now()->addMinutes(15),
    ]);

    // Other teacher tries to scan
    $response = $this->actingAs($otherTeacherUser)
        ->postJson('/api/attendance/scan', [
            'token' => $qr->token,
        ]);

    $response->assertForbidden()
        ->assertJsonFragment(['message' => 'QR jadwal ini bukan untuk Anda']);
});

test('student cannot scan if device not bound', function () {
    $studentUser = User::factory()->create(['user_type' => 'student']);
    $studentUser->studentProfile()->create(['class_id' => $this->class->id, 'nis' => 'S2']);

    $qr = Qrcode::create([
        'token' => Str::uuid(),
        'schedule_id' => $this->schedule->id,
        'type' => 'student',
        'is_active' => true,
        'expires_at' => now()->addMinutes(15),
    ]);

    $response = $this->actingAs($studentUser)
        ->postJson('/api/attendance/scan', [
            'token' => $qr->token,
        ]);

    $response->assertStatus(422)
        ->assertJsonFragment(['message' => 'Device belum terdaftar']);
});
